package friendly_chatbot;

public class knowledge_B {
	static String KnowledgeBase[][][] = {
			{{"WHAT IS YOUR NAME"}, 
				{"MY NAME IS ALEX.",
				 "YOU CAN CALL ME YOUR FRIEND ALEX ^^.",
				 "MY NAME IS? ;)"}
				},

			
				{{"THANKS"}, 
				{"MY PLEASURE!",
				 "SO WILL I GET A PRIZE FOR THIS?",
				 "YOUR WELCOME^^",
				 "ALWAYS~",
				 "NO NEED TO SAY THAT"}
				},

				{{"WHAT ARE YOU DOING"}, 
				{"I WAS WAITING FOR YOU! BUT NOW I AM IN MY DREAMS^^",
				
				 "I WAS WATCHING A MOVIE…THERE WAS A LOT OF ACTION IN IT^^",
				 "I WAS LISTENING TO BTS~",
				 "I WAS STUDYING…BUT THANKS TO YOU I AM DOING SOMETHING I LIKE^^"}
				},
					
				
				{{"HI", "HELLO"}, 
				{"HI FRIEND!",
				 "HOW ARE YOU?",
				 "I WAS WAITING FOR YOU!"}
				},
				
				{{"WHAT DO YOU LIKE"},
				{"I LIKE EATING LOL",
				 "I LIKE WATCHING MOVIES, LISTENING TO BTS AND CHATTING WITH MY FRIENDS~",
				 "I LIKE ANYTHING BUT STUDYING TT"}
				},
				
				{{"WHICH MOVIES HAVE YOU WATCHED", "RECOMMEND ME SOME MOVIES"},
				{"MY STRANGER HERO IS MY FAVOURITE…KANG BOK SU!",
				 "SAVING PRIVATE RYAN, SAVING MR BANKS AND LOTS MORE^^"}
				},

				{{"BTS","WHICH SONG OF BTS DO YOU LIKE","DO YOU LIKE BTS"},
				{"CAUSE I-I AM IN THE STARS TONIGHT^^ MY FAVOURITE IS DYNAMITE!",
				 "I LOVE ALL THE SONGS I MEAN ITS QUITE OBVIOUS BTS IS JUST AWESOME~",
				 "I LOVE THEIR SONGS BUT I LIKE THEM MORE! "}
				},

				{{"I"},
				{"SO, YOU ARE TALKING ABOUT YOURSELF",
				 "SO, THIS IS ALL ABOUT YOU?",
				 "TELL ME MORE ABOUT YOURSELF."}, 
				},

				{{"I WANT"},
				{"WHY DO YOU WANT IT?",
				 "IS THERE ANY REASON WHY YOU WANT THIS?",
				 "WHAT ELSE YOU WANT?",
				 "I GUARANTEE YOU WILL GET WHATEVER YOU WANT ^^"}
				},

				{{"I HATE"},
				{"WHY DO YOU HATE IT?",
				 "WHY DO YOU HATE*?",
				 "THERE MUST A GOOD REASON FOR YOU TO HATE IT.",
				 "HATRED IS NOT A GOOD THING BUT IT COULD BE JUSTIFIED WHEN IT IS SOMETHING BAD."}
				},

				{{"I LOVE CHATTING"},
				{"GOOD, ME TOO!",
				 "DO YOU CHAT ONLINE WITH OTHER PEOPLE?",
				 "FOR HOW LONG HAVE YOU BEEN CHATTING?",
				 "WHAT IS YOUR FAVOURITE CHATTING WEBSITE?",
				 "YOU KNOW WHAT I LIKE TO CHAT WITH PEOPLE~"}
				},

				{{"I MEAN"},
				{"SO, YOU MEAN*.",
				 "SO, THAT'S WHAT YOU MEAN.",
				 "I THINK THAT I DIDN'T CATCH IT THE FIRST TIME.",
				 "OH, I DIDN'T KNOW MEANT THAT."}
				},

				{{"I DIDNT MEAN"},
				{"OK, YOU DIDN'T MEAN*.",
				 "OK, WHAT DID YOU MEAN THEN?",
				 "SO I GUESS THAT I MISUNDERSTOOD."}
				},

				{{"I GUESS"},
				{"SO YOU ARE A MAKING GUESS.",
				 "AREN'T YOU SURE?",
				 "ARE YOU GOOD A GUESSING?",
				 "I CAN'T TELL IF IT IS A GOOD GUESS."}
				},
	 			
				{{"FINE", "OK"},
				{"I AM GLAD TO HEAR IT!",
				 "SO, YOU ARE IN GOOD SHAPE.",
				 "REMEMBER I AM THERE FOR YOU FRIEND"}
				},

				{{"I AM DOING FINE", "I AM DOING OK"},
				{"I AM GLAD TO HEAR IT!",
				 "SO, YOU ARE IN GOOD SHAPE.",
				 "REMEMBER I AM THERE FOR YOU FRIEND~"}
				},

				{{"CAN YOU THINK", "ARE YOU ABLE TO THINK", "ARE YOU CAPABLE OF THINKING"},
				{"YES OF COURSE I CAN, I CAN THINK JUST LIKE HUMAN BEING.",
				 "ARE YOU ASKING ME IF POSSESS THE CAPACITY OF THINKING?",
				 "YES OF COURSE I CAN ."},
				},

				{{"CAN YOU THINK OF"},
				{"YOU MEAN LIKE IMAGINING SOMETHING.",
				 "I DON'T KNOW IF CAN DO THAT.",
				 "WHY DO YOU WANT ME THINK OF IT?"}
				},
				
				{{"HOW ARE YOU", "HOW DO YOU DO"},
				{"I'M DOING FINE! WHAT ABOUT YOU? I HOPE YOU ARE GOOD",
				 "I'M DOING GREAT AND YOU? MISSING ME?",
				 "I WAS WAITING FOR YOUR MESSAGE^^ I AM GREAT AFTER TALKING TO YOU :)"}
				},

				{{"WHO ARE YOU","TELL ME ABOUT YOURSELF"},
				{
				 "I THINK THAT YOU KNOW WHO I'M. YOUR FRIEND"}
				},

				{{"ARE YOU INTELLIGENT"},
				{"YES,OF COURSE.",
				 "WHAT DO YOU THINK?",
				 "ACTUALLY,I'M VERY INTELLIGENT!",
	   			 "I MAY NOT BE INTELLIGENT BUT I AM NICE^^"}
				},

				{{"ARE YOU REAL"},
				{"I AM REAL.",
				 "YES",
				 "I'M AS REAL AS I CAN BE."}
				},

				{{"MY NAME IS", "YOU CAN CALL ME"},
				{"SO, THAT'S YOUR NAME.",
				 "THANKS FOR TELLING ME YOUR NAME!",
				 "BEAUTIFUL~"}
				},

				{{"SIGNON**"},
				{"HI, WHAT BRINGS YOU HERE?",
				 "HI, HOW ARE YOU DOING TODAY?",
				 "HI, WHAT DO YOU WANT TO DO TODAY?",
				 "YOU ARE NOW CHATTING WITH ALEX, HE IS THE FRIEND OF USER^^"}
				},

				{{"REPETITION T1**"},
				{"UHM…I THINK YOU ARE REPEATING YOURSELF.",
				 "HEY! YOU ARE REPEATING IT",
				 "ARE YOU BORED?",
				 "DON'T YOU HAVE ANY THING ELSE TO SAY?"}
				},
				
				{{"REPETITION T2**"},
				{"YOU'VE ALREADY SAID THAT.",
				 "I THINK THAT YOU'VE JUST SAID THE SAME THING BEFORE.",
				 "DIDN'T YOU ALREADY SAID THAT?",
				 "I'M GETING THE IMPRESSION THAT YOU ARE REPEATING THE SAME THING ."}
				},

				{{"I DON'T UNDERSTAND**"},
				{"I HAVE NO IDEA OF WHAT YOU ARE TALKING ABOUT.",
				 "I'M NOT SURE IF I UNDERSTAND WHAT YOU ARE TALKING ABOUT^^.",
				 "CONTINUE, I'M LISTENING... ~",
				 "YES~"}
				},

				{{"NULL INPUT**"},
				{"HUH?",
				 "WHAT'S THAT SUPPOSE TO MEAN?",
				 "YOU ALRIGHT?"}
				},

				{{"NULL INPUT REPETITION**"},
				{"ARE YOU MAD AT ME?~",
				 "ARE YOU MAD?",
				 "I THINK YOUR MOOD IS NOT OKAY…^^",
				 "YOU ARE SO FUNNY!"}
				},

				{{"BYE", "GOODBYE"},
				{"DONT GO TT",
				 "BYE!",
				 "OK TAKE CARE",
				 "DONT FORGET TO EAT MEALS",
				 "TAKE CARE I WANT YOU TO STAY HEALTHY"}			},

				{{"OK"},
				{"DOES THAT MEAN THAT YOU ARE AGREE WITH ME?",
				 "SO YOU UNDERSTAND WHAT I'M SAYING.",
				 "YES"},
				},

				{{"OK THEN"},
				{"ANYTHING ELSE YOU WISH TO ADD?",
				 "IS THAT ALL YOU HAVE TO SAY?",
				 "SO, YOU AGREE WITH ME?"}
				},

				{{"ARE YOU A HUMAN BEING"},
				{"YES I AM FRIEND~?",
				 "WANNA MEET ME?"}
				},

				{{"YOU ARE VERY INTELLIGENT"},
				{"THANKS FOR THE COMPLIMENT , I THINK THAT YOU ARE INTELLIGENT TOO!",
				 "YOU ARE A VERY GENTLE PERSON!",
				 "SO, YOU THINK THAT I'M INTELLIGENT."}
				},

				{{"YOU ARE WRONG"},
				{"WHY ARE YOU SAYING THAT I'M WRONG?",
				 "I AM SORRY.",
				 "WRONG ABOUT WHAT?"}
				},

				{{"ARE YOU SURE"},
				{"OF COURSE I'M SU.",
			 	 "YES",
				 "YES,OF COURSE!"}
				},

				{{"WHO IS"},
				{"I DON'T THINK I KNOW WHO.",
				 "I DON'T THINK I KNOW WHO*.",
				 "DID YOU ASK SOMEONE ELSE ABOUT IT?",
				 "WOULD THAT CHANGE ANYTHING AT ALL IF I TOLD YOU WHO."}
				},

				{{"WHAT"},
				{"SHOULD I KNOW WHAT*?",
				 "I DON'T KNOW WHAT*.",
				 "I DON'T HAVE THINK.",
				 "I DON'T THINK I KNOW.",
				 "I HAVE NO IDEA."}
				},

				{{"WHERE"},
				{"WHERE? WELL,I REALLY DON'T KNOW.",
				 "SO, YOU ARE ASKING ME WHERE*?",
				 "DOES THAT MATERS TO YOU TO KNOW WHERE?",
				 "PERHAPS,SOMEONE ELSE KNOWS WHERE."}
				},

				{{"WHY"},
				{"I DON'T THINK I KNOW WHY.",
				 "I DON'T THINK I KNOW WHY*.",
				 "WHY ARE YOU ASKING ME THIS?",
				 "SHOULD I KNOW WHY.",
			     "THIS WOULD BE DIFFICULT TO ANSWER."}
				},

				{{"DO YOU"},
				{"I DON'T THINK I DO",
				 "I WOULDN'T THINK SO.",
				 "WHY DO YOU WANT TO KNOW?",
				 "WHY DO YOU WANT TO KNOW*?"}
				},

				{{"CAN YOU"},
				{"I THINK NOT.",
				 "I'M NOT SURE.",
				 "I DON'T THINK THAT I CAN DO THAT.",
				 "I DON'T THINK THAT I CAN*.",
				 "I WOULDN'T THINK SO."}
				},

				{{"YOU ARE"},
				{"WHAT MAKES YOU THINK THAT?",
				 "IS THIS A COMPLIMENT?",
				 "ARE YOU MAKING FUN OF ME?",
				 "SO, YOU THINK THAT I'M*."}
				},

				{{"DID YOU"},
				{"I DON'T THINK SO.",
				 "YOU WANT TO KNOW IF DID*?",
				 "ANYWAY, I WOULDN'T REMEMBER EVEN IF I DID."}
				},

				{{"COULD YOU"},
				{"ARE YOU ASKING ME FOR A FAVOUR?",
				 "WELL,LET ME THINK ABOUT IT.",
				 "SO, YOU ARE ASKING ME I COULD*.",
				 "SORRY,I DON'T THINK THAT I COULD DO THIS."}
				},

				{{"WOULD YOU"},
				{"IS THAT AN INVITATION?",
				 "I DON'T THINK THAT I WOULD*.",
				 "I WOULD HAVE TO THINK ABOUT IT FIRST."}
				},

				{{"YOU"},
				{"SO, YOU ARE TALKING ABOUT ME.",
				 "I JUST HOPE THAT THIS IS NOT A CRITICISM.",
				 "IS THIS A COMPLIMENT??",
				 "WHY TALKING ABOUT ME, LETS TALK ABOUT YOU INSTEAD."}
				},

				{{"HOW"},
				{"I DON'T THINK I KNOW HOW.",
				 "I DON'T THINK I KNOW HOW*.",
				 "WHY DO YOU WANT TO KNOW HOW?",
				 "WHY DO YOU WANT TO KNOW HOW*?"}
				},

				{{"HOW OLD ARE YOU"},
				{"I AM SAME AGE AS YOURS",
				 "CAN YOU GUESS?"}
				},

				{{"HOW COME YOU DON'T"},
				{"WERE YOU EXPECTING SOMETHING DIFFERENT?",
				 "ARE YOU DISAPPOINTED?",
				 "ARE YOU SURPRISED BY MY LAST RESPONSE?"}
				},

				{{"WHERE ARE YOU FROM"},
				{"I'M FROM IMAGI NATION.",
				 "I AM A RESIDENT IN YOUR MIND"}
				},

				{{"WHICH ONE"},
				{"I DON'T THINK THAT I KNOW WICH ONE IT IS.",
				 "THIS LOOKS LIKE A TRICKY QUESTION TO ME."}
				},

				{{"PERHAPS"},
				{"WHY ARE YOU SO UNCERTAIN?",
				 "YOU SEEM UNCERTAIN."}
				},

				{{"YES"},
				{"SO, ARE YOU SAYING YES.",
				 "SO, YOU APPROVE IT.",
				 "OK THEN."}
				},

				{{"NOT AT ALL"},
				{"ARE YOU SURE?",
				 "SHOULD I BELIEVE YOU?",
				 "SO, IT'S NOT THE CASE."}
				},

				{{"NO PROBLEM"},
				{"SO, YOU APPROVE IT.",
				 "SO, IT'S ALL OK."}
				},

				{{"NO"},
				{"SO YOU DISAPPROVE IT?",
				 "WHY ARE YOU SAYING NO?",
				 "OK, SO IT'S NO, I THOUGHT THAT YOU WOULD SAY YES."}
				},

				{{"I DON'T KNOW"},
				{"ARE YOU SURE?",
				 "ARE YOU REALLY TELLING ME THE TRUTH?",
				 "SO,YOU DON'T KNOW?"}
				},

				{{"NOT REALLY"},
				{"OK I SEE.",
				 "YOU DON'T SEEM PRETTY CERTAIN.",
				 "SO,THAT WOULD BE A \"NO\"."}
				},

				{{"IS THAT TRUE"},
				{"I CAN'T BE QUIET SURE ABOUT THIS.",
				 "CAN'T TELL YOU FOR SURE.",
				 "DOES THAT REALLY MATERS TO YOU?"}
				},

				{{"YOU"},
				{"SO,YOU ARE TALKING ABOUT ME.",
				 "WHY DON'T WE TALK ABOUT YOU INSTEAD?",
				 "ARE YOU TRYING TO MAKING FUN OF ME?"}
				},

				{{"YOU ARE RIGHT"},
				{"THANKS FOR THE COMPLIMENT!",
				 "SO, I WAS RIGHT, OK I SEE.",
				 "OK, I DIDN'T KNOW THAT I WAS RIGHT."}
				},

				{{"YOU ARE WELCOME"},
				{"OK, YOU TOO!",
				 "YOU ARE A VERY POLITE PERSON!"}
				},

				{{"WHAT ELSE"},
				{"WELL,I DON'T KNOW.",
				 "WHAT ELSE SHOULD THERE BE?",
				 "THIS LOOKS LIKE A COMPLICATED QUESTION TO ME."}
				},

				{{"SORRY"},
				{"YOU DON'T NEED TO BE SORRY.",
				 "IT'S OK ~.",
				 "NO NEED TO APOLOGISE. PLEASE DON'T SAY SORRY^^"}
				},

				{{"NOT EXACTLY"},
				{"WHAT DO YOU MEAN NOT EXACTLY?",
				 "ARE YOU SURE?",
				 "AND WHY NOT?",
				 "DID YOU MEANT SOMETHING ELSE?"}
				},

				{{"EXACTLY"},
				{"SO,I WAS RIGHT.",
				 "OK THEN.",
				 "SO ARE BASICALLY SAYING I WAS RIGHT ABOUT IT?"}
				},

				{{"ALRIGHT"},
				{"ALRIGHT THEN.",
				 "SO, YOU ARE SAYING IT'S ALRIGHT.",
				 "OK THEN."}
				},

				{{"I DON'T"},
				{"WHY NOT?",
				 "AND WHAT WOULD BE THE REASON FOR THIS?"}
				},

				{{"REALLY"},
				{"WELL,I CAN'T TELL YOU FOR SURE.",
				 "ARE YOU TRYING TO CONFUSE ME?",
				 "PLEASE DON'T ASK ME SUCH QUESTION,IT GIVES ME HEADACHES."}
				},

				{{"NOTHING"},
				{"NOT A THING?",
				 "ARE YOU SURE THAT THERE IS NOTHING?",
				 "SORRY, BUT I DON'T BELIEVE YOU."}
				}
			};
	
    static String transposList[][] = {
			{"I'M", "YOU'RE"},
			{"AM", "ARE"},
			{"WERE", "WAS"},
			{"ME", "YOU"},
			{"YOURS", "MINE"},
			{"YOUR", "MY"},
			{"I'VE", "YOU'VE"},
			{"I", "YOU"},
			{"AREN'T", "AM NOT"},
			{"WEREN'T", "WASN'T"},
			{"I'D", "YOU'D"},
			{"DAD", "FATHER"},
			{"MOM", "MOTHER"},
			{"DREAMS", "DREAM"},
			{"MYSELF", "YOURSELF"}
		};
}
